name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
#        django-version: ["2.2", "3.0", "3.1", "3.2", "4.0", "4.1"]
#        es-dsl-version: ["7.4"]
        es-version: ["7.13.4"]

    steps:
      - name: Install and Run Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: ${{ matrix.es-version }}

      - uses: actions/checkout@v2

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Pip Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements_test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_test.txt

      - name: Install tox
        run: python -m pip install tox-gh-actions
      - name: Run test suite
        run: tox -r
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"

      - name: Publish Coverage Report
        uses: codecov/codecov-action@v1
