name: CI OpenSearch

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        django-version: ["2.2", "3.0", "3.1", "3.2", "4.0", "4.1"]
        es-dsl-version: ["1.0.0", "2.0.1"]
        es-version: ['1', '2']

    services:
      elasticsearch:
        image: opensearchproject/opensearch:${{ matrix.es-version }}
        ports:
          - 9200:9200
        options: >-
          -e="http.host=0.0.0.0"
          -e="transport.host=127.0.0.1"
          -e="discovery.type=single-node"
          -e="plugins.security.disabled=true"
          --health-cmd="curl http://localhost:9200/_cluster/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v2

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Pip Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements_test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "Django==${{ matrix.django-version }}"
          python -m pip install "opensearch-py==${{ matrix.es-version }}"
          python -m pip install "opensearch-dsl==${{ matrix.es-dsl-version }}"
          python -m pip install -r requirements_test.txt

      - name: Run tests with Python ${{ matrix.python-version }} and Django ${{ matrix.django-version }} and opensearch-dsl ${{ matrix.es-dsl-version }}
        run: |
          TOX_ENV=$(echo "py${{ matrix.python-version }}-django-${{ matrix.django-version }}-es${{ matrix.es-dsl-version }}" | tr -d .)
          python -m tox -e $TOX_ENV -- --elasticsearch

      - name: Publish Coverage Report
        uses: codecov/codecov-action@v1
